#! /usr/bin/python

task_test_header = """
/*
 * Generated by gen-headers.py.
 */
"""

task_test_tmpl = """
#ifdef WO_TASK{0}
#define __woSetupTask{0} __woSetupTask(WO_{0});
#define __woRunTask{0} __woRunTask(WO_TASK{0}, WO_{0});
#else
#define __woSetupTask{0}
#define __woRunTask{0}
#endif
"""

def gen_tasks(size):
    out = file('include/wolffia-task-gen.h', 'wt')

    print >>out, task_test_header

    for i in range(size):
        print >>out, task_test_tmpl.format(i)

    print >>out, "#define WO_RunOS()\\"
    print >>out, "do {\\"

    for i in range(size):
        print >>out, "\t\t__woSetupTask{0}\\".format(i)

    print >>out, "\twhile(true) {\\"

    for i in range(size):
        print >>out, "\t\t__woRunTask{0}\\".format(i)

    print >>out, "\t}\\"
    print >>out, "} while(0)"
    
    out.close()

gen_tasks(100)