#! /usr/bin/python

wolffia_header = """
/*
 * Generated by gen-headers.py.
 */
"""

task_test_tmpl = """
#ifdef WO_TASK{0}
# define __woRunTask{0} __woRunTask(WO_{0}, WO_TASK{0})
#else
# define __woRunTask{0}
#endif
"""

listener_test_impl = """
#ifdef WO_LISTENER{0}
# define __woListener{0} __woListenerCase(WO_LISTENER{0})
#else
# define __woListener{0}
#endif
"""

def gen_tasks(size):
    out = file('include/wolffia-task-gen.h', 'wt')

    print >>out, wolffia_header

    ############################################################################

    for i in range(size):
        print >>out, task_test_tmpl.format(i+1)
        print >>out, listener_test_impl.format(i+1)

    ############################################################################

    print >>out, "#define __woRunBlock\\"

    for i in range(size):
        print >>out, "\t__woRunTask{0}\\".format(i+1)

    print >>out, "\t__woFinalTask"

    ############################################################################


    print >>out, "#define __woListenerBlock\\"

    for i in range(size):
        print >>out, "\t__woListener{0}\\".format(i+1)

    print >>out, "\t__woDefaultListenerCase"

    out.close()

gen_tasks(128)