
/*
 * Generated by gen-headers.py.
 */


#ifdef WO_TASK1
#define __woSetupTask1 __woSetupTask(WO_1);
#define __woRunTask1 __woRunTask(WO_1, WO_TASK1);
#else
#define __woSetupTask1
#define __woRunTask1
#endif


#ifdef WO_TASK2
#define __woSetupTask2 __woSetupTask(WO_2);
#define __woRunTask2 __woRunTask(WO_2, WO_TASK2);
#else
#define __woSetupTask2
#define __woRunTask2
#endif


#ifdef WO_TASK3
#define __woSetupTask3 __woSetupTask(WO_3);
#define __woRunTask3 __woRunTask(WO_3, WO_TASK3);
#else
#define __woSetupTask3
#define __woRunTask3
#endif


#ifdef WO_TASK4
#define __woSetupTask4 __woSetupTask(WO_4);
#define __woRunTask4 __woRunTask(WO_4, WO_TASK4);
#else
#define __woSetupTask4
#define __woRunTask4
#endif


#ifdef WO_TASK5
#define __woSetupTask5 __woSetupTask(WO_5);
#define __woRunTask5 __woRunTask(WO_5, WO_TASK5);
#else
#define __woSetupTask5
#define __woRunTask5
#endif


#ifdef WO_TASK6
#define __woSetupTask6 __woSetupTask(WO_6);
#define __woRunTask6 __woRunTask(WO_6, WO_TASK6);
#else
#define __woSetupTask6
#define __woRunTask6
#endif


#ifdef WO_TASK7
#define __woSetupTask7 __woSetupTask(WO_7);
#define __woRunTask7 __woRunTask(WO_7, WO_TASK7);
#else
#define __woSetupTask7
#define __woRunTask7
#endif


#ifdef WO_TASK8
#define __woSetupTask8 __woSetupTask(WO_8);
#define __woRunTask8 __woRunTask(WO_8, WO_TASK8);
#else
#define __woSetupTask8
#define __woRunTask8
#endif


#ifdef WO_TASK9
#define __woSetupTask9 __woSetupTask(WO_9);
#define __woRunTask9 __woRunTask(WO_9, WO_TASK9);
#else
#define __woSetupTask9
#define __woRunTask9
#endif


#ifdef WO_TASK10
#define __woSetupTask10 __woSetupTask(WO_10);
#define __woRunTask10 __woRunTask(WO_10, WO_TASK10);
#else
#define __woSetupTask10
#define __woRunTask10
#endif


#ifdef WO_TASK11
#define __woSetupTask11 __woSetupTask(WO_11);
#define __woRunTask11 __woRunTask(WO_11, WO_TASK11);
#else
#define __woSetupTask11
#define __woRunTask11
#endif


#ifdef WO_TASK12
#define __woSetupTask12 __woSetupTask(WO_12);
#define __woRunTask12 __woRunTask(WO_12, WO_TASK12);
#else
#define __woSetupTask12
#define __woRunTask12
#endif


#ifdef WO_TASK13
#define __woSetupTask13 __woSetupTask(WO_13);
#define __woRunTask13 __woRunTask(WO_13, WO_TASK13);
#else
#define __woSetupTask13
#define __woRunTask13
#endif


#ifdef WO_TASK14
#define __woSetupTask14 __woSetupTask(WO_14);
#define __woRunTask14 __woRunTask(WO_14, WO_TASK14);
#else
#define __woSetupTask14
#define __woRunTask14
#endif


#ifdef WO_TASK15
#define __woSetupTask15 __woSetupTask(WO_15);
#define __woRunTask15 __woRunTask(WO_15, WO_TASK15);
#else
#define __woSetupTask15
#define __woRunTask15
#endif


#ifdef WO_TASK16
#define __woSetupTask16 __woSetupTask(WO_16);
#define __woRunTask16 __woRunTask(WO_16, WO_TASK16);
#else
#define __woSetupTask16
#define __woRunTask16
#endif


#ifdef WO_TASK17
#define __woSetupTask17 __woSetupTask(WO_17);
#define __woRunTask17 __woRunTask(WO_17, WO_TASK17);
#else
#define __woSetupTask17
#define __woRunTask17
#endif


#ifdef WO_TASK18
#define __woSetupTask18 __woSetupTask(WO_18);
#define __woRunTask18 __woRunTask(WO_18, WO_TASK18);
#else
#define __woSetupTask18
#define __woRunTask18
#endif


#ifdef WO_TASK19
#define __woSetupTask19 __woSetupTask(WO_19);
#define __woRunTask19 __woRunTask(WO_19, WO_TASK19);
#else
#define __woSetupTask19
#define __woRunTask19
#endif


#ifdef WO_TASK20
#define __woSetupTask20 __woSetupTask(WO_20);
#define __woRunTask20 __woRunTask(WO_20, WO_TASK20);
#else
#define __woSetupTask20
#define __woRunTask20
#endif


#ifdef WO_TASK21
#define __woSetupTask21 __woSetupTask(WO_21);
#define __woRunTask21 __woRunTask(WO_21, WO_TASK21);
#else
#define __woSetupTask21
#define __woRunTask21
#endif


#ifdef WO_TASK22
#define __woSetupTask22 __woSetupTask(WO_22);
#define __woRunTask22 __woRunTask(WO_22, WO_TASK22);
#else
#define __woSetupTask22
#define __woRunTask22
#endif


#ifdef WO_TASK23
#define __woSetupTask23 __woSetupTask(WO_23);
#define __woRunTask23 __woRunTask(WO_23, WO_TASK23);
#else
#define __woSetupTask23
#define __woRunTask23
#endif


#ifdef WO_TASK24
#define __woSetupTask24 __woSetupTask(WO_24);
#define __woRunTask24 __woRunTask(WO_24, WO_TASK24);
#else
#define __woSetupTask24
#define __woRunTask24
#endif


#ifdef WO_TASK25
#define __woSetupTask25 __woSetupTask(WO_25);
#define __woRunTask25 __woRunTask(WO_25, WO_TASK25);
#else
#define __woSetupTask25
#define __woRunTask25
#endif


#ifdef WO_TASK26
#define __woSetupTask26 __woSetupTask(WO_26);
#define __woRunTask26 __woRunTask(WO_26, WO_TASK26);
#else
#define __woSetupTask26
#define __woRunTask26
#endif


#ifdef WO_TASK27
#define __woSetupTask27 __woSetupTask(WO_27);
#define __woRunTask27 __woRunTask(WO_27, WO_TASK27);
#else
#define __woSetupTask27
#define __woRunTask27
#endif


#ifdef WO_TASK28
#define __woSetupTask28 __woSetupTask(WO_28);
#define __woRunTask28 __woRunTask(WO_28, WO_TASK28);
#else
#define __woSetupTask28
#define __woRunTask28
#endif


#ifdef WO_TASK29
#define __woSetupTask29 __woSetupTask(WO_29);
#define __woRunTask29 __woRunTask(WO_29, WO_TASK29);
#else
#define __woSetupTask29
#define __woRunTask29
#endif


#ifdef WO_TASK30
#define __woSetupTask30 __woSetupTask(WO_30);
#define __woRunTask30 __woRunTask(WO_30, WO_TASK30);
#else
#define __woSetupTask30
#define __woRunTask30
#endif


#ifdef WO_TASK31
#define __woSetupTask31 __woSetupTask(WO_31);
#define __woRunTask31 __woRunTask(WO_31, WO_TASK31);
#else
#define __woSetupTask31
#define __woRunTask31
#endif


#ifdef WO_TASK32
#define __woSetupTask32 __woSetupTask(WO_32);
#define __woRunTask32 __woRunTask(WO_32, WO_TASK32);
#else
#define __woSetupTask32
#define __woRunTask32
#endif

#define __woRun()\
do {\
		__woSetupTask1\
		__woSetupTask2\
		__woSetupTask3\
		__woSetupTask4\
		__woSetupTask5\
		__woSetupTask6\
		__woSetupTask7\
		__woSetupTask8\
		__woSetupTask9\
		__woSetupTask10\
		__woSetupTask11\
		__woSetupTask12\
		__woSetupTask13\
		__woSetupTask14\
		__woSetupTask15\
		__woSetupTask16\
		__woSetupTask17\
		__woSetupTask18\
		__woSetupTask19\
		__woSetupTask20\
		__woSetupTask21\
		__woSetupTask22\
		__woSetupTask23\
		__woSetupTask24\
		__woSetupTask25\
		__woSetupTask26\
		__woSetupTask27\
		__woSetupTask28\
		__woSetupTask29\
		__woSetupTask30\
		__woSetupTask31\
		__woSetupTask32\
	while(true) {\
		__woRunTask1\
		__woRunTask2\
		__woRunTask3\
		__woRunTask4\
		__woRunTask5\
		__woRunTask6\
		__woRunTask7\
		__woRunTask8\
		__woRunTask9\
		__woRunTask10\
		__woRunTask11\
		__woRunTask12\
		__woRunTask13\
		__woRunTask14\
		__woRunTask15\
		__woRunTask16\
		__woRunTask17\
		__woRunTask18\
		__woRunTask19\
		__woRunTask20\
		__woRunTask21\
		__woRunTask22\
		__woRunTask23\
		__woRunTask24\
		__woRunTask25\
		__woRunTask26\
		__woRunTask27\
		__woRunTask28\
		__woRunTask29\
		__woRunTask30\
		__woRunTask31\
		__woRunTask32\
	}\
} while(0)
